<?php

namespace Database\Seeders;

use App\Domain\Leases\LeaseService;
use App\Models\HousingAuthority;
use App\Models\Lease;
use App\Models\Property;
use App\Models\Tenant;
use App\Models\Unit;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * The real Heads Up Enterprises portfolio.  [WP-07, FR-REG-01, FR-REG-02]
 *
 * 25 properties, 27 units, 27 tenants and 27 active leases in Macon, Bibb
 * County, Georgia, built from `database/data/portfolio.json` — which is itself
 * generated by `build_portfolio.py` from the client's Portfolio.xlsx and the 27
 * signed lease PDFs. Regenerate the JSON rather than editing it by hand.
 *
 * Not wired into DatabaseSeeder. That runs in production, and CLAUDE.md gates
 * real tenant data behind WP-00H (the HostGator host checklist) — so this is
 * invoked deliberately and refuses to run anywhere but local/testing:
 *
 *     php artisan db:seed --class=RealPortfolioSeeder
 *
 * Idempotent. Every write is keyed on a natural identifier, so a second run
 * updates in place rather than producing a second portfolio. Leases go through
 * LeaseService, never a direct insert, because that is where the active-lease
 * constraint and the unit-status side effect live (I-11).
 */
class RealPortfolioSeeder extends Seeder
{
    public function __construct(private readonly LeaseService $leases) {}

    /**
     * The operator's deliberate opt-in for a non-local load.
     *
     * Outside local/testing this seeder is off. It is not enough to be careful:
     * `db:seed` runs from deploy scripts, and a portfolio of real tenants must
     * not be able to appear on a host because a workflow called the wrong
     * class. Requiring a variable that exists only in the one shell that means
     * it keeps the accident impossible while leaving the deliberate act open.
     */
    private const PRODUCTION_OPT_IN = 'HUPM_ALLOW_REAL_DATA_LOAD';

    public function run(): void
    {
        if (! app()->environment(['local', 'testing']) && getenv(self::PRODUCTION_OPT_IN) !== '1') {
            $this->command?->error('RealPortfolioSeeder refused: this is real tenant data and WP-00H has not passed.');
            $this->command?->line('  Set '.self::PRODUCTION_OPT_IN.'=1 in the invoking shell to override deliberately.');

            return;
        }

        if (! app()->environment(['local', 'testing'])) {
            $this->command?->warn('Loading REAL TENANT DATA into '.app()->environment().' by explicit opt-in.');
        }

        $doc = $this->load();

        $authority = $this->seedAuthority($doc['housing_authority']);
        $properties = $this->seedProperties($doc['properties']);

        $units = $tenants = $created = $updated = 0;

        foreach ($doc['records'] as $record) {
            $property = $properties[$record['property']]
                ?? throw new RuntimeException("Unknown property {$record['property']} for {$record['key']}.");

            $unit = $this->seedUnit($property, $record['unit']);
            $units++;

            $tenant = $this->seedTenant($record['tenant']);
            $tenants++;

            $this->seedLease($record, $unit, $tenant, $authority) ? $created++ : $updated++;
        }

        $this->report($properties, $units, $tenants, $created, $updated, $doc['_meta']);
    }

    /** @return array<string, mixed> */
    private function load(): array
    {
        $path = database_path('data/portfolio.json');

        if (! is_file($path)) {
            throw new RuntimeException("Missing {$path}. Run: python database/data/build_portfolio.py");
        }

        return json_decode(file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    }

    /**
     * The real agency, replacing the placeholder from HousingAuthoritySeeder.
     *
     * `hupm:demo-wipe` deliberately keeps `housing_authorities` as reference
     * data, so the placeholder survives a wipe and would otherwise sit in the
     * dropdown next to the real agency forever. It is removed only once nothing
     * references it — an authority in use is left alone rather than orphaning a
     * lease.
     */
    private function seedAuthority(array $data): HousingAuthority
    {
        $authority = HousingAuthority::updateOrCreate(['name' => $data['name']], [
            'contact_name' => $data['contact_name'],
            'contact_email' => $data['contact_email'],
            'contact_phone' => $data['contact_phone'],
            'remittance_type' => $data['remittance_type'], // [GATE Q-2]
        ]);

        HousingAuthority::query()
            ->whereKeyNot($authority->id)
            ->where('name', 'like', '%placeholder%')
            ->whereDoesntHave('leases')
            ->delete();

        return $authority;
    }

    /** @return array<string, Property> keyed by property name */
    private function seedProperties(array $rows): array
    {
        $properties = [];

        foreach ($rows as $row) {
            $properties[$row['name']] = Property::updateOrCreate(
                ['name' => $row['name']],
                collect($row)->except('name')->all(),
            );
        }

        return $properties;
    }

    /**
     * Through the relation, not Unit::updateOrCreate.
     *
     * `property_id` is absent from Unit::$fillable, so passing it as a
     * mass-assignment attribute would be dropped in silence and the insert
     * would fail on a NULL foreign key. The relation sets the key itself.
     */
    private function seedUnit(Property $property, array $data): Unit
    {
        // Matches the (property_id, unit_number) unique index.
        return $property->units()->updateOrCreate(
            ['unit_number' => $data['unit_number']],
            collect($data)->except('unit_number')->all(),
        );
    }

    /**
     * Tenants are matched on name.
     *
     * There is no natural key on `tenants` — email is the obvious candidate and
     * every one of these 27 is NULL (Q-4). All 27 names are distinct in this
     * portfolio, and the guard below fails loudly rather than silently merging
     * two people if that ever stops being true.
     */
    private function seedTenant(array $data): Tenant
    {
        $match = ['first_name' => $data['first_name'], 'last_name' => $data['last_name']];

        if (Tenant::where($match)->count() > 1) {
            throw new RuntimeException(
                "More than one tenant named {$data['first_name']} {$data['last_name']}; cannot match on name.",
            );
        }

        return Tenant::updateOrCreate($match, collect($data)->except(['first_name', 'last_name'])->all());
    }

    /**
     * @return bool true when the lease was created, false when updated
     */
    private function seedLease(array $record, Unit $unit, Tenant $tenant, HousingAuthority $authority): bool
    {
        $attributes = $record['lease'] + [
            'unit_id' => $unit->id,
            'tenant_id' => $tenant->id,
            // AC-REG-05: a subsidised lease must name the agency paying its
            // portion; a market-rate one must not carry a stale reference.
            'housing_authority_id' => $record['lease']['is_subsidised'] ? $authority->id : null,
        ];

        $this->assertPortionsSum($record['key'], $attributes);

        // The tenancy, not the paperwork: one active lease per unit (D-03), so
        // the unit plus its start date identifies it.
        $existing = Lease::where('unit_id', $unit->id)
            ->where('start_date', $attributes['start_date'])
            ->first();

        if ($existing) {
            $this->leases->update($existing, $attributes);

            return false;
        }

        $this->leases->create($attributes);

        return true;
    }

    /**
     * AC-REG-03, enforced here because LeaseService is reached directly.
     *
     * The rule normally lives in LeaseRequest, which a seeder never passes
     * through. Comparing as strings rather than floats keeps invariant I-10
     * intact — bccomp, not ==.
     */
    private function assertPortionsSum(string $key, array $lease): void
    {
        $sum = bcadd($lease['tenant_portion'], $lease['ha_portion'], 2);

        if (bccomp($sum, $lease['total_contract_rent'], 2) !== 0) {
            throw new RuntimeException(
                "Lease {$key}: portions {$sum} do not sum to {$lease['total_contract_rent']}.",
            );
        }
    }

    private function report(array $properties, int $units, int $tenants, int $created, int $updated, array $meta): void
    {
        if (! $this->command) {
            return;
        }

        $rent = DB::table('leases')->where('status', 'active')->sum('total_contract_rent');
        $ha = DB::table('leases')->where('status', 'active')->sum('ha_portion');

        // outputComponents(), not ->components: the property itself is
        // protected on InteractsWithIO and a seeder is outside the command.
        $io = $this->command->outputComponents();

        $this->command->newLine();
        $io->twoColumnDetail('<fg=green>Properties</>', (string) count($properties));
        $io->twoColumnDetail('Units', (string) $units);
        $io->twoColumnDetail('Tenants', (string) $tenants);
        $io->twoColumnDetail('Leases', "{$created} created, {$updated} updated");
        $io->twoColumnDetail('Monthly contract rent', '$'.number_format((float) $rent, 2));
        $io->twoColumnDetail('  of which housing authority', '$'.number_format((float) $ha, 2));
        $this->command->newLine();

        $io->warn('Loaded with known data issues:');
        foreach ($meta['known_issues'] as $issue) {
            $this->command->line("  <fg=yellow>-</> {$issue}");
        }
    }
}
