<?php

use App\Domain\Documents\DocumentVault;
use App\Domain\Ledger\LedgerService;
use App\Domain\Maintenance\MaintenanceService;
use App\Models\Lease;
use App\Models\Payment;
use App\Models\SignatureRequest;
use App\Models\Tenant;
use App\Models\Unit;
use App\Models\User;
use App\Support\Money;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| TC-SEC-01 — horizontal privilege escalation  [WP-34, TDD §6.1 A01, I-9]
|--------------------------------------------------------------------------
|
| Two residents, both legitimate, both signed in. Every route that takes an
| identifier is tried by the wrong one.
|
| **The answer is always 404, never 403.** A 403 says "that exists, but not for
| you", which tells Bianca that Anselm is a resident here — the same fact a
| debt collector, an ex-partner or a process server would like to know. BR-20
| and invariant I-9 make the two indistinguishable from outside.
|
| This is written as one file rather than left to the per-feature suites on
| purpose. Those test that a feature scopes correctly; this asks a different
| question — *is there any identifier-bearing route where it does not* — and
| the answer has to be checked against the router, not against a list somebody
| maintains by hand. The route audit at the bottom is the part that fails when
| a new route is added without ownership scoping.
*/

uses(RefreshDatabase::class);

beforeEach(function () {
    Storage::fake('local');

    $this->admin = User::factory()->create(['role' => 'admin']);

    $this->anselm = secResident('Anselm', 'Wrzesniewski');
    $this->bianca = secResident('Bianca', 'Okonkwo');
});

/**
 * A resident with everything a resident can own: lease, document, ticket,
 * payment and a ledger with real rows in it.
 *
 * Named `secResident` rather than `makeResident` because NoticeTest already
 * declares one -- a Pest helper is a plain global function, so two files that
 * each pass alone fatal the moment they load together.
 *
 * @return object{tenant: Tenant, user: User, lease: Lease}
 */
function secResident(string $first, string $last): object
{
    $tenant = Tenant::factory()->create(['first_name' => $first, 'last_name' => $last]);
    $user = User::factory()->create(['role' => 'tenant', 'tenant_id' => $tenant->id]);

    $lease = new Lease;
    $lease->forceFill([
        'unit_id' => Unit::factory()->create()->id,
        'tenant_id' => $tenant->id,
        'start_date' => '2026-01-01',
        'end_date' => '2026-12-31',
        'total_contract_rent' => '900.00',
        'tenant_portion' => '300.00',
        'ha_portion' => '600.00',
        'rent_due_day' => 1,
        'grace_period_days' => 5,
        'status' => 'active',
    ]);
    $lease->save();

    return (object) ['tenant' => $tenant, 'user' => $user, 'lease' => $lease];
}

function ownedDocument(object $resident)
{
    return app(DocumentVault::class)->store(
        $resident->tenant,
        UploadedFile::fake()->createWithContent('lease.pdf', "%PDF-1.4\n%stub\n")
            ->mimeType('application/pdf'),
        ['category' => 'current_lease', 'title' => 'Lease'],
        test()->admin,
    );
}

function ownedTicket(object $resident)
{
    return app(MaintenanceService::class)->submit($resident->lease, [
        'category' => 'plumbing',
        'description' => 'The kitchen tap drips continuously and will not close.',
        'permission_to_enter' => true,
        'preferred_contact' => 'email',
    ], [], $resident->user);
}

function ownedPayment(object $resident): Payment
{
    return Payment::factory()->create([
        'lease_id' => $resident->lease->id,
        'tenant_id' => $resident->tenant->id,
        'amount' => '300.00',
        'method' => 'echeck',
        'gateway' => 'authorize_net',
        'gateway_transaction_id' => (string) random_int(100000, 999999),
        'idempotency_key' => (string) Str::uuid(),
        'submitted_at' => now(),
    ]);
}

/*
 |--------------------------------------------------------------------------
 | The four surfaces named in the DoD
 |--------------------------------------------------------------------------
 */

it('TC-SEC-01 returns 404 when a resident opens another resident document', function () {
    $document = ownedDocument($this->anselm);

    $this->actingAs($this->bianca->user)
        ->get("/portal/documents/{$document->id}")
        ->assertNotFound();
});

it('TC-SEC-01 returns 404 on a download even with a valid signature', function () {
    $document = ownedDocument($this->anselm);

    /*
     | The signature is generated by the application, so it is genuine. This is
     | the case a signed URL invites you to get wrong: it is tempting to treat
     | the signature as the authorisation, and then a link forwarded in an
     | email — or lifted from a shared browser — works for whoever holds it.
     |
     | The signature only makes a copied URL expire. Ownership is what makes it
     | private, and it is checked separately.
    */
    $url = URL::temporarySignedRoute(
        'portal.documents.download',
        now()->addMinutes(5),
        ['document' => $document->id],
    );

    $this->actingAs($this->bianca->user)->get($url)->assertNotFound();
});

it('TC-SEC-01 returns 404 when a resident opens another resident maintenance ticket', function () {
    $ticket = ownedTicket($this->anselm);

    $this->actingAs($this->bianca->user)
        ->get("/portal/maintenance/{$ticket->id}")
        ->assertNotFound();
});

it('TC-SEC-01 refuses to let a resident confirm another resident ticket as complete', function () {
    $ticket = ownedTicket($this->anselm);

    // A write, not a read. Confirming somebody else's repair closes a ticket
    // about a home you have never been in.
    $this->actingAs($this->bianca->user)
        ->post("/portal/maintenance/{$ticket->id}/confirm", ['satisfied' => true])
        ->assertNotFound();
});

it('TC-SEC-01 scopes the ledger to the signed-in resident, showing no row of another', function () {
    /*
     | The ledger takes no identifier — there is no /portal/ledger/{id} to
     | attack. So the escalation to test is not a wrong id, it is whether the
     | query is scoped at all: a controller that forgot its `where` returns
     | every row in the table to everybody, and the page still looks correct
     | to whoever opens it.
    */
    app(LedgerService::class)->postCharge(
        $this->anselm->lease,
        'rent',
        'tenant',
        Money::fromString('300.00'),
        'March rent for Anselm',
        $this->anselm->lease->id.':2026-03:rent:tenant',
        period: '2026-03',
    );

    $this->actingAs($this->bianca->user)
        ->get('/portal/ledger')
        ->assertOk()
        ->assertDontSee('Anselm', escape: false)
        ->assertDontSee('March rent for Anselm', escape: false);
});

it('TC-SEC-01 refuses a payment posted against another resident lease', function () {
    /*
     | The payments escalation is a write, not a read, and the identifier is in
     | the BODY rather than the URL — which is why it needs its own test. A
     | route-parameter policy never sees this one: `lease_id` arrives as a form
     | field, validated as `['required', 'integer']`, and an integer is exactly
     | what somebody else's lease id is.
     |
     | Paying somebody else's rent is not obviously an attack until you notice
     | the ledger row it would write, the balance it would move, and the
     | statement it would appear on.
    */
    $before = Payment::count();

    $response = $this->actingAs($this->bianca->user)->postJson('/portal/pay', [
        'lease_id' => $this->anselm->lease->id,
        'amount' => '300.00',
        'idempotency_key' => (string) Str::uuid(),
    ]);

    expect($response->status())->not->toBe(200, 'A payment against another resident lease was accepted.');
    expect(Payment::count())->toBe($before, 'A payment row was written for another resident lease.');
});

it('TC-SEC-01 shows a resident no payment of another in their own history', function () {
    $theirs = ownedPayment($this->anselm);
    ownedPayment($this->bianca);

    $body = (string) $this->actingAs($this->bianca->user)
        ->get('/portal/ledger')->assertOk()->getContent();

    expect(str_contains($body, (string) $theirs->gateway_transaction_id))
        ->toBeFalse('Another resident payment reference appeared in this resident ledger.');
});

it('TC-SEC-01 returns 404 when a resident opens another resident signature request', function () {
    $signature = new SignatureRequest;
    $signature->forceFill([
        'document_id' => ownedDocument($this->anselm)->id,
        'tenant_id' => $this->anselm->tenant->id,
        'user_id' => $this->anselm->user->id,
        'status' => 'pending',
        'sent_at' => now(),
        'expires_at' => now()->addDays(7),
    ])->save();

    // A signature request is a lease or a renewal with somebody's name on it,
    // and the screen shows the document itself before it shows the button.
    $this->actingAs($this->bianca->user)
        ->get("/portal/sign/{$signature->id}")
        ->assertNotFound();
});

/*
 |--------------------------------------------------------------------------
 | Wrong ROLE is a different answer
 |--------------------------------------------------------------------------
 */

it('I-9 answers 403 for the wrong role, keeping it distinct from 404 for the wrong owner', function () {
    /*
     | The two mechanisms must stay distinguishable, and the reason is not
     | pedantry. 404 everywhere would hide a misconfigured role behind what
     | looks like a missing page, and nobody would ever find it. 403 everywhere
     | would confirm the existence of other people's records.
     |
     | Role is a fact about the caller, which they already know. Ownership is a
     | fact about somebody else.
    */
    $this->actingAs($this->bianca->user)->get('/admin')->assertForbidden();

    $this->actingAs($this->admin)->get('/portal')->assertForbidden();
});

/*
 |--------------------------------------------------------------------------
 | The part that catches the route added next year
 |--------------------------------------------------------------------------
 */

it('TC-SEC-01 leaves no portal route taking an identifier without an ownership check', function () {
    /*
     | Read from the router, not from a list. Every portal route with a model
     | parameter must resolve that model through a policy or an owned
     | relationship — a route that does neither returns whatever id it is
     | handed.
     |
     | This does not attack each route; it asserts the ones that exist are the
     | ones covered above. When somebody adds /portal/statements/{statement},
     | this fails with its name in the message, and the fix is to test it.
    */
    $covered = [
        'portal.documents.show',
        'portal.documents.download',
        'portal.maintenance.show',
        'portal.maintenance.confirm',
        'portal.notices.attachment',
        'portal.sign.show',
        'portal.sign.store',
        'portal.sign.consent',
        'portal.sign.scrolled',
    ];

    $parameterised = collect(app('router')->getRoutes()->getRoutes())
        ->filter(fn ($route) => str_starts_with((string) $route->getName(), 'portal.'))
        ->filter(fn ($route) => $route->parameterNames() !== [])
        ->map(fn ($route) => (string) $route->getName())
        ->values()
        ->all();

    $uncovered = array_values(array_diff($parameterised, $covered));

    expect($uncovered)->toBe([], 'A portal route takes an identifier and TC-SEC-01 does not '
        .'exercise it: '.implode(', ', $uncovered).'. Add it to this file, then to $covered.');
});
